{{- if eq (include "natsie-chart.hasManagedSigningKey" .) "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "natsie-chart.secretName" . }}
  labels:
    {{- include "natsie-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  signing_key: {{ .Values.bot.signingKey | quote }}
{{- end }}
{{- if eq (include "natsie-chart.hasManagedNatsContexts" .) "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "natsie-chart.natsCtxSecretName" . }}
  labels:
    {{- include "natsie-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range .Values.natsContexts.inline }}
  {{ .name }}.json: {{ .content | quote }}
{{- end }}
{{- end }}
{{- if eq (include "natsie-chart.hasManagedMattermostToken" .) "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "natsie-chart.mattermostTokenSecretName" . }}
  labels:
    {{- include "natsie-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.bot.mattermost.token | quote }}
{{- end }}
